# Generated by Django 5.2.5 on 2026-03-01 18:58

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
import tinymce.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('district', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='FeeHead',
            fields=[
                ('fee_head_account_id', models.AutoField(primary_key=True, serialize=False)),
                ('fee_head_name', models.CharField(max_length=255)),
                ('fee_head_amount', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Logo',
            fields=[
                ('college_id', models.AutoField(primary_key=True, serialize=False)),
                ('college_name', models.CharField(max_length=255)),
                ('logo_path', models.CharField(blank=True, max_length=255, null=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logos/')),
                ('uploaded_by', models.CharField(blank=True, max_length=255, null=True)),
                ('uploaded_date', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Province',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('province', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(default='2024', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'feeapp_user',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Clerk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clerk_id', models.CharField(blank=True, max_length=20, unique=True)),
                ('clerk_name', models.CharField(max_length=255)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('position', models.CharField(blank=True, max_length=50, null=True)),
                ('cnic', models.CharField(blank=True, max_length=15, null=True)),
                ('gender', models.CharField(blank=True, max_length=10, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='clerk', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Challan',
            fields=[
                ('challan_number', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('challan_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(default='UNPAID', max_length=50)),
                ('payment_status', models.CharField(choices=[('PAID', 'Paid'), ('UNPAID', 'Unpaid'), ('PARTIALLY_PAID', 'Partially Paid')], default='UNPAID', max_length=20)),
                ('original_total_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('remaining_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('download_status', models.CharField(choices=[('PENDING', 'Pending Download'), ('DOWNLOADED', 'Downloaded'), ('SUSPENDED', 'Suspended'), ('NOT_APPLICABLE', 'Not Applicable')], default='NOT_APPLICABLE', max_length=20)),
                ('challan_generation_date', models.DateField()),
                ('html_content', models.TextField(blank=True, null=True)),
                ('challan_file', models.FileField(blank=True, null=True, upload_to='challan_files/')),
                ('disciplines', models.TextField(blank=True, null=True)),
                ('semesters', models.TextField(blank=True, null=True)),
                ('one_bill_number', models.CharField(blank=True, max_length=50, null=True)),
                ('created_by_clerk', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_challans', to='feeapp.clerk')),
            ],
        ),
        migrations.CreateModel(
            name='ClerkOTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('otp_code', models.CharField(max_length=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_used', models.BooleanField(default=False)),
                ('clerk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feeapp.clerk')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('payment_id', models.AutoField(primary_key=True, serialize=False)),
                ('amount_paid', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_date', models.DateField()),
                ('payment_method', models.CharField(choices=[('Bank', 'Bank'), ('Online', 'Online')], max_length=50)),
                ('transaction_id', models.CharField(blank=True, max_length=100, null=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('challan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feeapp.challan')),
            ],
        ),
        migrations.CreateModel(
            name='Programs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=255)),
                ('short_description', tinymce.models.HTMLField()),
                ('image', models.FileField(default=None, max_length=250, null=True, upload_to='program_images/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Programs',
            },
        ),
        migrations.CreateModel(
            name='CourseGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('short_description', tinymce.models.HTMLField()),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('user_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('program_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='feeapp.programs')),
            ],
        ),
        migrations.CreateModel(
            name='RegisteredStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('morning', 'Morning'), ('evening', 'Evening')], default='morning', max_length=10)),
                ('college_roll_no', models.CharField(blank=True, max_length=50, null=True)),
                ('university_roll_no', models.CharField(blank=True, max_length=50, null=True)),
                ('registration_no', models.CharField(blank=True, max_length=50, null=True)),
                ('name', models.CharField(max_length=255)),
                ('cnic_no', models.CharField(max_length=20, unique=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='std_photos/')),
                ('date_of_birth', models.DateField()),
                ('mobile_no', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('father_name', models.CharField(max_length=255)),
                ('father_cnic', models.CharField(max_length=20)),
                ('father_mobile_no', models.CharField(max_length=15)),
                ('father_occupation', models.CharField(max_length=255)),
                ('guardian_name', models.CharField(blank=True, max_length=255, null=True)),
                ('guardian_cnic', models.CharField(blank=True, max_length=20, null=True)),
                ('guardian_contact_no', models.CharField(blank=True, max_length=15, null=True)),
                ('permanent_address', models.TextField()),
                ('postal_address', models.TextField()),
                ('city', models.CharField(max_length=100)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10)),
                ('religion', models.CharField(choices=[('Islam', 'Islam'), ('Christian', 'Christian'), ('Sikh', 'Sikh'), ('Other', 'Other')], max_length=50)),
                ('hafiz_e_quran', models.BooleanField(default=False)),
                ('hafiz_doc', models.FileField(blank=True, null=True, upload_to='hafiz_doc/')),
                ('blood_group', models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('O+', 'O+'), ('O-', 'O-'), ('AB+', 'AB+'), ('AB-', 'AB-')], default='A+', max_length=10)),
                ('marital_status', models.CharField(choices=[('Married', 'Married'), ('Unmarried', 'Unmarried'), ('Divorced', 'Divorced')], max_length=10)),
                ('disability_status', models.BooleanField(default=False)),
                ('disability_type', models.CharField(blank=True, max_length=100, null=True)),
                ('related_to_worker', models.BooleanField(default=False)),
                ('worker_name', models.CharField(blank=True, max_length=255, null=True)),
                ('worker_relation', models.CharField(blank=True, max_length=30, null=True)),
                ('worker_payscale', models.CharField(blank=True, max_length=50, null=True)),
                ('worker_status', models.BooleanField(default=False)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('district', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='feeapp.district')),
                ('province', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='feeapp.province')),
            ],
        ),
        migrations.AddField(
            model_name='challan',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feeapp.registeredstudent'),
        ),
        migrations.CreateModel(
            name='SchemeOfStudy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feeapp.coursegroup')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feeapp.programs')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feeapp.session')),
            ],
            options={
                'verbose_name_plural': 'Schemes of Study',
            },
        ),
        migrations.CreateModel(
            name='SchemeCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester_year', models.PositiveIntegerField(help_text='1–2 for Intermediate, 1–8 for BS')),
                ('course_code', models.CharField(blank=True, max_length=50, null=True)),
                ('course_name', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(choices=[('new', 'New'), ('old', 'Old')], default='new', max_length=10)),
                ('scheme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='feeapp.schemeofstudy')),
            ],
        ),
        migrations.AddField(
            model_name='registeredstudent',
            name='scheme_of_study',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='feeapp.schemeofstudy'),
        ),
        migrations.CreateModel(
            name='ChallanFeeHead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date_of_generation', models.DateField()),
                ('challan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feeapp.challan')),
                ('fee_head_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feeapp.feehead')),
            ],
            options={
                'unique_together': {('fee_head_account', 'challan')},
            },
        ),
        migrations.CreateModel(
            name='Installment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('installment_number', models.PositiveIntegerField(choices=[(1, '1'), (2, '2'), (3, '3')])),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('due_date', models.DateField()),
                ('status', models.CharField(choices=[('PAID', 'Paid'), ('UNPAID', 'Unpaid')], default='UNPAID', max_length=20)),
                ('installment_challan', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='installment_info', to='feeapp.challan')),
                ('original_challan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='installments', to='feeapp.challan')),
            ],
            options={
                'ordering': ['installment_number'],
                'unique_together': {('original_challan', 'installment_number')},
            },
        ),
        migrations.CreateModel(
            name='FeeHeadProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fee_head', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feeapp.feehead')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feeapp.programs')),
            ],
            options={
                'unique_together': {('fee_head', 'program')},
            },
        ),
    ]
