# Generated by Django 5.2.5 on 2026-03-01 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clerk',
            name='clerk_id',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
