# Generated by Django 5.2.5 on 2026-03-03 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeapp', '0002_alter_clerk_clerk_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='challan',
            name='challan_generation_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
