# Generated by Django 5.2.5 on 2026-03-03 14:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeapp', '0003_challan_challan_generation_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClerkActivityHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('first_challan_number', models.CharField(blank=True, max_length=50, null=True)),
                ('last_challan_number', models.CharField(blank=True, max_length=50, null=True)),
                ('clerk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_history', to='feeapp.clerk')),
            ],
            options={
                'verbose_name_plural': 'Clerk Activity Histories',
                'ordering': ['-date', '-time'],
            },
        ),
        migrations.CreateModel(
            name='ClerkLoginHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('login_time', models.TimeField()),
                ('logout_time', models.TimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='login_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Clerk Login Histories',
                'ordering': ['-date', '-login_time'],
            },
        ),
    ]
