# Generated by Django 5.2.5 on 2026-03-13 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeapp', '0004_clerkactivityhistory_clerkloginhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='clerkloginhistory',
            name='logout_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
